services:
  chatbot-ollama:
    image: ghcr.io/ivanfioravanti/chatbot-ollama:main
    container_name: chatbot-ollama
    ports:
      - '3000:3000'
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  nextchat:
    image: yidadaa/chatgpt-next-web
    container_name: nextchat
    ports:
      - '3001:3000'
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - ENABLE_OLLAMA=1
      - CUSTOM_MODELS=+deepseek-coder:1.3b,+deepseek-coder:6.7b
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  big-agi:
    image: ghcr.io/enricoros/big-agi:latest
    container_name: big-agi
    ports:
      - '3002:3000'
    environment:
      - BIG_AGI_OLLAMA_API_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
